#pragma once

#define COLOR_WHITE                          Color(0xffffffff)
#define COLOR_BLACK                          Color(0, 0, 0, 255)
#define COLOR_BACKGROUND                     Color(0x00006F00)
#define COLOR_TEXT                           COLOR_WHITE
#define COLOR_TEXT_AT_CURSOR                 Color(0xB0B0FFFF)
#define COLOR_LIST_HIGH                      Color(0x40D070FF)
#define COLOR_LIST_HIGH_AT_CURSOR            Color(0x40D0BBFF)
#define COLOR_LIST                           Color(0x00FF00FF)
#define COLOR_LIST_AT_CURSOR                 Color(0xDDFFDDFF)
#define COLOR_LIST_SKIPPED                   Color(0x888800FF)
#define COLOR_LIST_SKIPPED_AT_CURSOR         Color(0x8888AAFF)
#define COLOR_LIST_SELECTED_INJECT           Color(0xAAFF00FF)
#define COLOR_LIST_SELECTED_INJECT_AT_CURSOR Color(0xCCCC60FF)
#define COLOR_LIST_INJECT                    Color(0x99FF00FF)
#define COLOR_LIST_INJECT_AT_CURSOR          Color(0x99FFBBFF)
#define COLOR_LIST_DANGER                    Color(0xFF0000FF)
#define COLOR_LIST_DANGER_AT_CURSOR          Color(0xFF4060FF)
#define COLOR_LIST_RESTORE_SUCCESS           Color(0xFFFFFFFF)
#define COLOR_LIST_RESTORE_SUCCESS_AT_CURSOR Color(0xBBBBEEFF)
#define COLOR_INFO                           Color(0x88CC88FF)
#define COLOR_INFO_AT_CURSOR                 Color(0x88CCCCFF)
#define COLOR_CURRENT_BS                     Color(0xFFBB33FF)
#define COLOR_CURRENT_BS_AT_CURSOR           Color(0xFFFF99FF)
#define COLOR_KEY                            Color(0xFF3333FF)
#define COLOR_KEY_S                          Color(0xFF666600)
#define COLOR_KEY_C                          Color(0xFF0000FF)
#define COLOR_BG_SUCCESS                     Color(0x00DD55FF)
#define COLOR_BG_OK                          Color(0x00AA0099)
#define COLOR_BG_WR                          Color(0xBB7F0000)
#define COLOR_BG_KO                          Color(0x7F000000)
#define COLOR_BG_ERROR                       Color(0xAA0000FF)
#define COLOR_LIST_ICON_AT_CURSOR            Color(0x55FF55FF)
#define COLOR_LIST_SELECTED_SELECT_ICON      Color(0x99FF99ff)
