name: CI-Release

on: [ push, pull_request ]

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build Docker Image (with layer caching)
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          load: true  # This replaces 'docker build' and exports the image to the local daemon
          tags: builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build artifacts
        run: |
          docker run --rm -v ${PWD}:/project builder:latest make release -j$(nproc)
      - name: Upload Aroma version
        uses: actions/upload-artifact@v7
        with:
          name: SaveMiiProcessMod-Aroma
          path: build/Aroma/*
          if-no-files-found: warn
      - name: Upload HBL version
        uses: actions/upload-artifact@v7
        with:
          name: SaveMiiProcessMod-HBL
          path: build/HBL/*
          if-no-files-found: warn
